# Dependencies
markdown:            kramdown

redcarpet:
  extensions: ["tables", "fenced_code_block"]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

exclude:      ["*.Rmd"]


# Setup
title:               Relacyjne systemy organizacji danych
tagline:             'kurs dla studentów WAT'
description:         'Relacyjne systemy organizacji danych'
url:                 https://sebkaz-teaching.github.io/rsod
baseurl:             "/rsod"             
paginate:            5

# About/contact
author:
  name:              Sebastian Zając
  url:               https://sebastianzajac.pl
  email:             sebastian.zajac@wat.edu.pl

# Custom vars
version:             1.0.0
