CREATE TABLE klienci (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dane_osobowe TEXT,
    adres TEXT,
    produkty TEXT
);

INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Wiśniewski', 'ul. Lipowa 1,', 'Słuchawki, Router, Drukarka, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Grabowska', 'ul. Mickiewicza  ,', 'Telefon, Laptop, Kamera internetowa, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Czerwińska', 'ul. Słoneczna  ,', 'Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Król', 'ul. Szkolna 27,', 'Monitor, Tablet, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Kowalski', 'ul. Polna ,', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Wójcik', 'ul. Spacerowa 30,', 'Mysz, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Baran', 'ul. Lipowa , 30-400', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Kowalski', 'ul. Mickiewicza  , 60-100', 'Monitor, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Czerwińska', 'ul. Lipowa  , 35-100 Poznań', 'Laptop, Słuchawki, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Pawlak', 'ul. Spacerowa ,', 'Mysz, Kamera internetowa, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Grabowska', 'ul. Słoneczna 9,', 'Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Król', 'ul. Słoneczna  ,', 'Słuchawki, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Kubiak', 'ul. Szkolna  ,  Katowice', 'Mysz, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Kamińska', 'ul. Szkolna , 35-100', 'Laptop, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Nowak', 'ul. Słoneczna , 20-001', 'Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Wójcik', 'ul. Polna 20,', 'Telefon, Laptop, Drukarka, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Wójcik', 'ul. Lipowa 47,', 'Mysz, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Krawczyk', 'ul. Polna 6,', 'Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Baran', 'ul. Długa  , 20-001 Gdańsk', 'Monitor, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Czerwińska', 'ul. Parkowa 29,', 'Mysz, Drukarka, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Pawlak', 'ul. Słoneczna  ,', 'Słuchawki, Monitor, Laptop, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Baran', 'ul. Parkowa 16,', 'Monitor, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Kubiak', 'ul. Spacerowa ,', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Czerwińska', 'ul. Słoneczna  , 70-100 Tychy', 'Laptop, Telefon, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Wieczorek', 'ul. Różana 17,', 'Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Malinowski', 'ul. Lipowa 1, 80-001', 'Kamera internetowa, Klawiatura, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Wiśniewski', 'ul. Spacerowa , 60-100', 'Drukarka, Słuchawki, Tablet, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Kowalski', 'ul. Parkowa ,   Gdańsk', 'Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Walczak', 'ul. Długa 49,  Rzeszów', 'Słuchawki, Tablet, Monitor, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Kowalski', 'ul. Szkolna ,', 'Klawiatura, Słuchawki, Monitor, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Olga Lewandowska', 'ul. Lipowa ,', 'Tablet, Laptop, Monitor, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Walczak', 'ul. Spacerowa  ,   Gdańsk', 'Słuchawki, Laptop, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Wójcik', 'ul. Szkolna  ,  Kraków', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Król', 'ul. Mickiewicza 19,   Lublin', 'Drukarka, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Olga Pawlak', 'ul. Polna , 70-100 Rzeszów', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Walczak', 'ul. Spacerowa  ,   Lublin', 'Tablet, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Lewandowska', 'ul. Orla 39,   Łódź', 'Kamera internetowa, Telefon, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Wieczorek', 'ul. Orla  ,  Lublin', 'Monitor, Kamera internetowa, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Król', 'ul. Spacerowa  ,', 'Laptop, Kamera internetowa, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Agnieszka Malinowski', 'ul. Szkolna  ,', 'Router, Słuchawki, Drukarka, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Czerwińska', 'ul. Słoneczna 2,  Poznań', 'Klawiatura, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Kowalski', 'ul. Orla , 80-001', 'Klawiatura, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Jan Wieczorek', 'ul. Mickiewicza  ,', 'Drukarka, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Wójcik', 'ul. Mickiewicza  , 60-100', 'Mysz, Laptop, Słuchawki, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Baran', 'ul. Długa ,', 'Drukarka, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Wójcik', 'ul. Polna  ,   Tychy', 'Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Czerwińska', 'ul. Lipowa 44,', 'Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Nowak', 'ul. Szkolna ,   Warszawa', 'Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Szymański', 'ul. Różana ,', 'Drukarka, Router, Słuchawki, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Pawlak', 'ul. Różana ,   Szczecin', 'Telefon, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Wójcik', 'ul. Lipowa  , 43-100 Tychy', 'Router, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Olga Król', 'ul. Szkolna  ,', 'Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Nowak', 'ul. Różana  , 90-001 Warszawa', 'Router, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Maj', 'ul. Spacerowa ,', 'Laptop, Kamera internetowa, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Baran', 'ul. Długa 9,  Tychy', 'Laptop, Telefon, Monitor, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Krawczyk', 'ul. Polna  , 70-100 Rzeszów', 'Klawiatura, Drukarka, Monitor, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Kubiak', 'ul. Mickiewicza  ,', 'Monitor, Kamera internetowa, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Wieczorek', 'ul. Różana 17,  Tychy', 'Mysz, Router, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Wiśniewski', 'ul. Lipowa ,', 'Mysz, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Zając', 'ul. Szkolna 38, 00-001', 'Telefon, Klawiatura, Laptop, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Wieczorek', 'ul. Orla ,', 'Monitor, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Wiśniewski', 'ul. Polna ,  Tychy', 'Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Maj', 'ul. Spacerowa  , 60-100', 'Klawiatura, Router, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Król', 'ul. Spacerowa  , 90-001', 'Kamera internetowa, Monitor, Router, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Baran', 'ul. Polna 12, 40-001', 'Router, Monitor, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Król', 'ul. Słoneczna 22,', 'Telefon, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Król', 'ul. Lipowa 34,', 'Monitor, Laptop, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Jan Wieczorek', 'ul. Polna  ,', 'Kamera internetowa, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Malinowski', 'ul. Mickiewicza 43,', 'Mysz, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Nowak', 'ul. Polna ,  Gdańsk', 'Router, Tablet, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Dorota Zając', 'ul. Długa 49, 70-100 Kraków', 'Słuchawki, Laptop, Drukarka, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Wójcik', 'ul. Orla  ,', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Grabowska', 'ul. Spacerowa , 90-001', 'Telefon, Klawiatura, Monitor, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Kubiak', 'ul. Spacerowa  , 20-001', 'Drukarka, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Lis', 'ul. Lipowa  ,', 'Tablet, Kamera internetowa, Router, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Lis', 'ul. Orla 3, 90-001', 'Laptop, Router, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Marek Wójcik', 'ul. Różana 31, 43-100', 'Mysz, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Zając', 'ul. Słoneczna  , 35-100', 'Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Olga Wiśniewski', 'ul. Parkowa 21,', 'Telefon, Monitor, Router, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Nowak', 'ul. Szkolna ,  Gdańsk', 'Klawiatura, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Zając', 'ul. Lipowa  ,  Katowice', 'Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Czerwińska', 'ul. Różana ,', 'Kamera internetowa, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Krawczyk', 'ul. Słoneczna  ,', 'Słuchawki, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Wójcik', 'ul. Polna 48,', 'Monitor, Telefon, Tablet, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Lis', 'ul. Polna ,', 'Monitor, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Nowak', 'ul. Spacerowa 15,', 'Laptop, Klawiatura, Mysz');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Wójcik', 'ul. Parkowa  , 60-100', 'Klawiatura, Mysz, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Nowak', 'ul. Słoneczna  ,   Rzeszów', 'Mysz, Kamera internetowa, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Wiśniewski', 'ul. Szkolna ,', 'Telefon, Tablet, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Pawlak', 'ul. Polna ,', 'Kamera internetowa, Mysz, Laptop, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Anna Lis', 'ul. Lipowa 19,', 'Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Lewandowska', 'ul. Lipowa  , 20-001', 'Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Czerwińska', 'ul. Różana 47,   Gdańsk', 'Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Wiśniewski', 'ul. Parkowa ,   Kraków', 'Klawiatura, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Kamińska', 'ul. Szkolna  ,', 'Klawiatura, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Maj', 'ul. Szkolna , 20-001 Warszawa', 'Kamera internetowa, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Zofia Wieczorek', 'ul. Parkowa ,', 'Router, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Natalia Malinowski', 'ul. Szkolna  , 40-001 Rzeszów', 'Kamera internetowa, Router, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Zając', 'ul. Różana  , 70-100 Szczecin', 'Telefon, Tablet, Drukarka, Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Wiśniewski', 'ul. Orla 7,', 'Kamera internetowa');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Maj', 'ul. Słoneczna  ,', 'Telefon, Monitor, Kamera internetowa, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Kamińska', 'ul. Parkowa , 35-100', 'Drukarka, Mysz, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Adam Walczak', 'ul. Szkolna ,', 'Słuchawki, Kamera internetowa, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Kamil Czerwińska', 'ul. Długa 12,', 'Telefon, Klawiatura, Monitor, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Michał Baran', 'ul. Spacerowa  ,', 'Tablet, Telefon, Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Nowak', 'ul. Szkolna 43, 70-100 Poznań', 'Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Baran', 'ul. Orla  , 30-400 Warszawa', 'Kamera internetowa, Mysz, Laptop, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Wiśniewski', 'ul. Szkolna , 00-001', 'Laptop, Router, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Jan Grabowska', 'ul. Długa  , 35-100 Tychy', 'Tablet, Router');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Krawczyk', 'ul. Orla 17, 35-100', 'Drukarka, Kamera internetowa, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Karolina Malinowski', 'ul. Orla , 70-100 Poznań', 'Router, Drukarka, Mysz, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Walczak', 'ul. Długa 44,', 'Słuchawki, Monitor');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Rafał Lewandowska', 'ul. Słoneczna , 80-001', 'Mysz, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Andrzej Lewandowska', 'ul. Polna  ,', 'Telefon, Klawiatura');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Wójcik', 'ul. Lipowa ,   Poznań', 'Mysz, Laptop, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Malinowski', 'ul. Długa  , 35-100 Łódź', 'Laptop');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Katarzyna Malinowski', 'ul. Różana  ,', 'Klawiatura, Tablet');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Piotr Walczak', 'ul. Lipowa , 90-001', 'Kamera internetowa, Telefon, Klawiatura, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Maj', 'ul. Szkolna  , 35-100', 'Mysz, Drukarka');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Monika Malinowski', 'ul. Szkolna ,  Katowice', 'Laptop, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Ewa Szymański', 'ul. Orla  ,', 'Mysz, Słuchawki');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Paweł Zając', 'ul. Parkowa 20,', 'Klawiatura, Tablet, Telefon');
INSERT INTO klienci (dane_osobowe, adres, produkty) VALUES ('Tomasz Kubiak', 'ul. Spacerowa 27, 70-100', 'Klawiatura, Laptop, Mysz');
